package com.etatech.hashiya.core.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/** "Modern academic": neutral surfaces with one deep-teal brand color (#0B6E6E). */
internal val LightColors = lightColorScheme(
    primary = Color(0xFF0B6E6E),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD7ECEA),
    onPrimaryContainer = Color(0xFF002020),
    secondary = Color(0xFF4A6362),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE0F2EF),
    onSecondaryContainer = Color(0xFF0B3B3A),
    tertiary = Color(0xFF4B607C),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD3E4FF),
    onTertiaryContainer = Color(0xFF041C35),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFFFFF),
    onBackground = Color(0xFF0F1720),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF0F1720),
    surfaceVariant = Color(0xFFF1F4F5),
    onSurfaceVariant = Color(0xFF5B6770),
    outline = Color(0xFFD5DBDF),
    outlineVariant = Color(0xFFE3E8EB),
    inverseSurface = Color(0xFF2B3238),
    inverseOnSurface = Color(0xFFEEF1F3),
    inversePrimary = Color(0xFF7FD4D2),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF7F9FA),
    surfaceContainer = Color(0xFFF1F4F5),
    surfaceContainerHigh = Color(0xFFEBEEF0),
    surfaceContainerHighest = Color(0xFFE3E8EB)
)

internal val DarkColors = darkColorScheme(
    primary = Color(0xFF7FD4D2),
    onPrimary = Color(0xFF003737),
    primaryContainer = Color(0xFF004F4F),
    onPrimaryContainer = Color(0xFF9CF1EE),
    secondary = Color(0xFFB0CCCA),
    onSecondary = Color(0xFF1B3534),
    secondaryContainer = Color(0xFF1F3F3D),
    onSecondaryContainer = Color(0xFFCCE8E6),
    tertiary = Color(0xFFB3C8E8),
    onTertiary = Color(0xFF1C314B),
    tertiaryContainer = Color(0xFF334863),
    onTertiaryContainer = Color(0xFFD3E4FF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0E1417),
    onBackground = Color(0xFFDEE3E6),
    surface = Color(0xFF0E1417),
    onSurface = Color(0xFFDEE3E6),
    surfaceVariant = Color(0xFF1A2124),
    onSurfaceVariant = Color(0xFFBEC8CC),
    outline = Color(0xFF3A4448),
    outlineVariant = Color(0xFF2A3236),
    inverseSurface = Color(0xFFDEE3E6),
    inverseOnSurface = Color(0xFF2B3235),
    inversePrimary = Color(0xFF0B6E6E),
    surfaceContainerLowest = Color(0xFF090F11),
    surfaceContainerLow = Color(0xFF161D20),
    surfaceContainer = Color(0xFF1A2124),
    surfaceContainerHigh = Color(0xFF242B2E),
    surfaceContainerHighest = Color(0xFF2F3639)
)
